### ISSUE TITLE
关于时间线和note 结点速度不一和移位的bug

### ISSUE THREAD

**Issue by TRAfoer** [Selakz/TAKANA_Cubic#1]
长时间放置后会导致这个问题
（在学校没法测国庆回来群里说

**Comment by Selakz** [comment]
确认了是由于窗口比例被设为非16:9导致的；将通过增加调整分辨率的功能来尽可能保证在各设备上都能保持16:9的比例。在这之后，由于窗口比例不正确导致的该问题将不再考虑。
